#######################################
############  usuário  ################
#######################################


# Criar usuário
POST http://127.0.0.1:8000/usuario/ HTTP/1.1
content-type: application/json

{
    "id": 80,
    "nome": "bruna",
    "email": "teste@gmail.com",
    "senha": "265"
}

#######################################
# Pegar usuário pelo id
GET http://127.0.0.1:8000/usuario/80/ HTTP/1.1
content-type: application/json

####### Usuario pelo nome #############

GET http://127.0.0.1:8000/usuario/nome/bruna/
content-type: application/json


#######################################
############  endereço  ###############
#######################################

# Criar endereço
POST http://127.0.0.1:8000/80/endereco/ HTTP/1.1
content-type: application/json

{
    "rua": "Rua jose gomes ",
    "cep": "99999-999",
    "cidade": "Goiania",
    "estado": "GO"
}

#######################################

# Pegar endereço por id
GET http://127.0.0.1:8000/usuario/80/enderecos/
content-type: application/json

########################################
# Pegar endereço por dominio
GET http://127.0.0.1:8000/usuario/80/emails/gmail.com/ HTTP/1.1
content-type: application/json

########################################
DELETE http://127.0.0.1:8000/usuario/80/ HTTP/1.1
content-type: application/json

#######################################
############  produto  ################
#######################################

### Pegar produtos

GET http://127.0.0.1:8000/produtos/ HTTP/1.1
content-type: application/json

### Pegar 1 produto
GET http://127.0.0.1:8000/produtos/9 HTTP/1.1
content-type: application/json

### Criar produto
POST http://127.0.0.1:8000/produto/ HTTP/1.1
content-type: application/json

{
    "id": 10,
    "nome": "",
    "descricao": "Doce gelado",
    "preco": 9.99
}

#######################################
############  Carrinho  ################
#######################################

### Adiciona produto no carrinho do usuário

PUT http://127.0.0.1:8000/produto/ HTTP/1.1
content-type: application/json

{
    "id": 10,
    "nome": "",
    "descricao": "Doce gelado",
    "preco": 9.99
}